### ISSUE TITLE
Version alpha

### ISSUE THREAD

**Issue by iddar** [iddar/taco#1]
## TODO for this session

- [x] Support all methods 
  [GET, POST, PUT, DELETE, OPTIONS]
- [x] Routes
- [ ] response JSON, text, and HTML
- [ ] add Salsitas (middleware)

**Follow Kiss principle**
